### ISSUE TITLE
need to take contextPath into consideration when resolving bundle names

### ISSUE THREAD

**Issue by iampivot** [mwanji/humpty#4]
If i run my webapp with a contextPath other than /, I get an exception;

java.lang.IllegalArgumentException: There is no bundle named d/humpty/core.js

This is with the context path /frontend, and the path I'm trying to load the js resourse is then /frontend/humpty/core/js.

It looks like the internal string operations is forgetting to strip the context path from the path before resolving the path to a bundle config? The number of chars stripped from /frontend/humpty/core.js is 8 which is the length of /humpty/, resulting in d/humpty/core.js.

**Comment by mwanji** [comment]
Could you try using [this branch of humpty-servlet](https://github.com/mwanji/humpty-servlet/tree/handle_context_path)? It should fix the problem. If it works for you, I'll merge it into master and release it.

**Comment by mwanji** [comment]
Fixed in humpty-servlet by https://github.com/mwanji/humpty-servlet/commit/c339e0211c526cf2e6da7eaf5fd7e62629329129

Released in humpty-servlet 0.3.0, which I've submitted to Maven Central and should be available soon.

**Comment by iampivot** [comment]
Sorry, been off work for a while so couldn't test yet.

**Comment by mwanji** [comment]
No worries. Let me know if you have any more problems, but I've added some unit tests and tried it with my own application, so I'm fairly sure it should work for you as well.
